### ISSUE TITLE
Fails to create ZIP for S3

### ISSUE THREAD

**Issue by rgaudin** [openzim/gutenberg#122]
Latest [gutenberg run](https://farm.openzim.org/pipeline/5eec8b3bbb9b3d5f165ac366/debug) on the zimfarm failed while trying to create a ZIP file for S3 upload

``` py
Traceback (most recent call last):
  File "/usr/local/bin/gutenberg2zim", line 4, in <module>
    __import__('pkg_resources').run_script('gutenberg2zim==1.1.4', 'gutenberg2zim')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/EGG-INFO/scripts/gutenberg2zim", line 274, in <module>
    main(docopt(help, version=VERSION))
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/EGG-INFO/scripts/gutenberg2zim", line 235, in main
    optimizer_version=OPTIMIZER_VERSION,
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/gutenbergtozim/export.py", line 281, in export_all_books
    Pool(concurrency).map(dlb, books)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/gutenbergtozim/export.py", line 278, in dlb
    optimizer_version=optimizer_version,
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/gutenbergtozim/export.py", line 573, in export_book
    optimizer_version=optimizer_version,
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/gutenbergtozim/export.py", line 843, in handle_unoptimized_files
    optimizer_version=optimizer_version,
  File "/usr/local/lib/python3.6/dist-packages/gutenberg2zim-1.1.4-py3.6.egg/gutenbergtozim/s3.py", line 78, in upload_to_cache
    zipfl.write(fl, arcname=fl.name)
  File "/usr/lib/python3.6/zipfile.py", line 1617, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/usr/lib/python3.6/zipfile.py", line 507, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'static/9454_p34ssht2.png'
```

**Comment by eshellman** [comment]
that file is a corrupt image file that isn't referenced in the corresponding html file.

**Comment by eshellman** [comment]
also possibly relevant - this book was repaired in april 2020 to address 172 images with spaces in the name
