### ISSUE TITLE
unexpected end of data

### ISSUE THREAD

**Issue by zhihengGet** [openzim/gutenberg#226]
1. followed instruction but i cannto download python-dev , no such packages to download
```
is only available from another source
      However the following packages replace it:
        python2-dev python2 python-dev-is-python3
      
      E: Package 'python-dev' has no installation candidate
```
3. run hatch shell then gutenberg command

[gutenberg2zim::2024-08-31 11:17:18,004] INFO:  Skipping already parsed file cache/epub/146/pg146.rdf for book id 146
[gutenberg2zim::2024-08-31 11:17:18,033] INFO:  Skipping already parsed file cache/epub/147/pg147.rdf for book id 147
[gutenberg2zim::2024-08-31 11:17:18,075] INFO:  Skipping already parsed file cache/epub/148/pg148.rdf for book id 148
[gutenberg2zim::2024-08-31 11:17:18,106] INFO:  Skipping already parsed file cache/epub/149/pg149.rdf for book id 149
[gutenberg2zim::2024-08-31 11:17:18,134] INFO:  Skipping already parsed file cache/epub/150/pg150.rdf for book id 150
Traceback (most recent call last):
  File "/home/abc/.local/share/hatch/env/virtual/gutenberg2zim/HXfwz31n/gutenberg2zim/bin/gutenberg2zim", line 8, in <module>
    sys.exit(entrypoint.main())
             ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/nicej/Documents/git_proj/books/gutenberg/src/gutenberg2zim/entrypoint.py", line 191, in main
    parse_and_fill(rdf_path=rdf_path, only_books=books)
  File "/mnt/c/Users/nicej/Documents/git_proj/books/gutenberg/src/gutenberg2zim/rdf.py", line 40, in parse_and_fill
    for rdf_member in rdf_tarfile:
  File "/usr/lib/python3.11/tarfile.py", line 2475, in __iter__
    tarinfo = self.next()
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/tarfile.py", line 2344, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data

**Comment by benoit74** [comment]
1. Of course, python-dev availability is varying from linux distro to linux distro ... and I'm not sure it is really required ; I've opened https://github.com/openzim/gutenberg/issues/227 to track the change required

2. Looks like the tar file you got is corrupted ... is it a systematic failure ? 

If you only want to create a ZIM, I advise to install docker and use the docker image (it is unfortunately undocumented yet, see https://github.com/openzim/gutenberg/issues/228 I've just opened). Basically `docker run -it --rm -v $(pwd)/output:/data ghcr.io/openzim/gutenberg:latest gutenberg2zim -m /data` is going to create a ZIM in the output subfolder of current directory (not fully tested, hence the issue to do this correctly, but I do not have time to do it now)

**Comment by benoit74** [comment]
Please also note the recent warning I've just added on https://github.com/openzim/gutenberg/blob/main/README.md

**Comment by benoit74** [comment]
But anyway, this will have to be investigated as well: do we have an issue with the tar file?

**Comment by benoit74** [comment]
No repro, closing, feel free to reopen if you have more info on how to reproduce the bug
